/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.delfin.views;


import com.delfin.classes.Numbers;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author tibe
 */
public class MainView extends javax.swing.JFrame {

    private List<JComboBox> combos;
    private String[] comboBoxItems = new String [] {"0" , "1", "2" , "3" , "4" ,"5" , "6" , "7" , "8","9"};
    private DefaultComboBoxModel comboBoxModel;
    Numbers numbers = new Numbers();
    ItemListener itemListener; 
            
    /**
     * Creates new form MainView
     */
    public MainView(int numberOfdigits) {
        
        numbers.setNumberOfDigits(numberOfdigits);
        numbers.setRandomNumber(numbers.generateRandomNumber());
        numbers.setDigitos(numbers.digitsRandomNumber(numbers.getRandomNumber()));
        
        //Validar que el numero no tenga digitos rpetidos
        boolean flag = false;
        do{
            flag = false;
           
            for (int i = 0; i < numberOfdigits - 1; i++) {
                for (int j = i + 1; j < numberOfdigits; j++) {
                    if(numbers.getDigitos()[i] == numbers.getDigitos()[j]){
                         numbers.setRandomNumber(numbers.generateRandomNumber());
                         numbers.setDigitos(numbers.digitsRandomNumber(numbers.getRandomNumber()));
                         flag = true;
                    }
                }
            }
        }while(flag);
 
        initComponents();
        textAreaHisto.setEditable(false);
        lblNumero.setText("Numero: 0");
        
        itemListener= new ItemListener() {
            public void itemStateChanged(ItemEvent itemEvent) {
                String aux = "Número: ";
                for (int i = 0; i < combos.size(); i++) {
                 aux =aux + combos.get(i).getSelectedItem().toString() + " ";
                }
                lblNumero.setText(aux);
                lblNumero.updateUI();
            }
        };
       
        combos = new ArrayList<JComboBox>();
        
        for (int i = 0; i < numberOfdigits; i++) {
            this.comboBoxModel = new DefaultComboBoxModel<>(comboBoxItems);
            JComboBox combo = new JComboBox();
            combo.setModel(comboBoxModel);
            combo.addItemListener(itemListener);
            panel.add(combo);
            combos.add(combo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnValidate = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaHisto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExit.setText("SALIR ");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnValidate.setText("VALIDAR");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 51, 102));
        lblInfo.setText("Famas: 0 y Puntos 0");

        lblNumero.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblNumero.setText("********");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Punto y Fama");

        panel.setLayout(new java.awt.GridLayout(1, 3));
        jTabbedPane4.addTab("Juego", panel);

        textAreaHisto.setColumns(20);
        textAreaHisto.setRows(5);
        jScrollPane2.setViewportView(textAreaHisto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel3);

        jTabbedPane4.addTab("Historial", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       MenuView mv=new MenuView();
       mv.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
           int[] combosValues = new int[numbers.getNumberOfdigits()];
            String auxHistory = "";
            for (int i = 0; i < combos.size(); i++) {
                combosValues[i] = Integer.parseInt(combos.get(i).getSelectedItem().toString());
                auxHistory = auxHistory + combos.get(i).getSelectedItem().toString();
            }

           numbers.validatePuntosYFamas(combosValues);
           if(numbers.getIsWinner()){
                  lblInfo.setText("GANASTE");
           }else{
           lblInfo.setText("Famas: " + numbers.getFamas()+ " y Puntos: " + numbers.getPuntos());
        
           }
           textAreaHisto.setText( textAreaHisto.getText() + "Numero: " + auxHistory + "\n" +
                   "Famas: " + numbers.getFamas()+ " y Puntos: " + numbers.getPuntos() +
                   "\n ----------------------------------------------------------------- \n");
           textAreaHisto.updateUI();
           lblInfo.updateUI();
           
    }//GEN-LAST:event_btnValidateActionPerformed

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnValidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea textAreaHisto;
    // End of variables declaration//GEN-END:variables
}
